config/routes.rb
FlashquestApi::Application.routes.draw do

  resources :samples

  root 'home#index'

  get '/ping' => 'application#ping'

  namespace :admin do
    resources :factual, only: [:index]
    resources :setup, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :businesses do
      resources :branches do
        resources :quest_descriptions
        resources :reward_descriptions
      end
    end


  end

  namespace :api do namespace :v1 do
    resources :devices,         only: [:create], defaults: { format: 'json' }

    get   'me',
      to: 'me#index',  as: :me,         defaults: { format: 'json' }

    patch 'me',
      to: 'me#update', as: :my_profile, defaults: { format: 'json' }

    get 'me/feed',
      to: 'me#feed', as: :me_feed, defaults: { format: 'json' }

    get 'me/activities',
      to: 'me#activities', as: :me_activities, defaults: { format: 'json' }

    # Aliases for /me (to act like RESTfull resource)
    # :id is simply ignored (since header token is used to find the Person)
    get 'me/:id', to: 'me#index', defaults: { format: 'json' } # alias for GET /me
    put 'me/:id', to: 'me#update', defaults: { format: 'json' } # alias for PATCH /me


    post '/branches/:branch_id/quest_descriptions/:quest_description_id/quests',
      to: 'quests#create', as: :new_quest, defaults: { format: 'json' }

    post '/branches/:branch_id/reward_descriptions/:reward_description_id/rewards',
      to: 'rewards#create', as: :new_reward, defaults: { format: 'json' }

    resources :activities,        only: [:show], defaults: { format: 'json' }

    resources :businesses,      only: [:index, :show], defaults: { format: 'json' } do
      resources :branches,      only: [:index], defaults: { format: 'json' }
      resources :patrons,       only: [:index], defaults: { format: 'json' }
      resources :people,        only: [:index], defaults: { format: 'json' }
      resources :activities,      only: [:index], defaults: { format: 'json' }
      resources :quests,        only: [:index], defaults: { format: 'json' }
      resources :photoquests,   only: [:index], controller: :quests, defaults: { format: 'json', type: 'photo' }
      resources :commentquests, only: [:index], controller: :quests, defaults: { format: 'json', type: 'comment' }
      resources :rewards,       only: [:index], defaults: { format: 'json' }
    end

    resources :people, only: [:index, :show], defaults: { format: 'json' } do
      resources :feed,          only: [:index], defaults: { format: 'json' }
      resources :activities,    only: [:index], defaults: { format: 'json' }
      resources :branches,      only: [:index, :show], defaults: { format: 'json' }
      resources :businesses,    only: [:index, :show], defaults: { format: 'json' }
      resources :quests,        only: [:index], defaults: { format: 'json' }
      resources :photoquests,   only: [:index], controller: :quests, defaults: { format: 'json', type: 'photo' }
      resources :commentquests, only: [:index], controller: :quests, defaults: { format: 'json', type: 'comment' }
      resources :approvals,     only: [:index], defaults: { format: 'json' }
      resources :comments,      only: [:index], defaults: { format: 'json' }
      resources :rewards,       only: [:index], defaults: { format: 'json' }
    end

    resources :branches,        only: [:index, :show], defaults: { format: 'json' } do
      resources :patrons,       only: [:index], defaults: { format: 'json' }
      resources :people,        only: [:index], defaults: { format: 'json' }
      resources :activities,      only: [:index], defaults: { format: 'json' }
      resources :quests,        only: [:index], defaults: { format: 'json' }
      resources :photoquests,   only: [:index], controller: :quests, defaults: { format: 'json', type: 'photo' }
      resources :commentquests, only: [:index], controller: :quests, defaults: { format: 'json', type: 'comment' }
      resources :approvals,     only: [:index], defaults: { format: 'json' }
      resources :comments,      only: [:index], defaults: { format: 'json' }
      resources :rewards,       only: [:index], defaults: { format: 'json' }
    end

    resources :patrons,         only: [:index, :show], defaults: { format: 'json' } do
      resources :activities,      only: [:index], defaults: { format: 'json' }
      resources :quests,        only: [:index], defaults: { format: 'json' }
      resources :photoquests,   only: [:index], controller: :quests, defaults: { format: 'json', type: 'photo' }
      resources :commentquests, only: [:index], controller: :quests, defaults: { format: 'json', type: 'comment' }
      resources :approvals,     only: [:index], defaults: { format: 'json' }
      resources :comments,      only: [:index], defaults: { format: 'json' }
      resources :rewards,       only: [:index], defaults: { format: 'json' }
    end

    resources :quests, only: [:index, :show, :destroy], defaults: { format: 'json' } do
      resources :approvals,     only: [:index, :create, :destroy], defaults: { format: 'json' }
      resources :comments,      only: [:index, :create, :destroy], defaults: { format: 'json' }
    end

    resources :rewards, only: [:index, :show], defaults: { format: 'json' }
  end end
end

app/models/business/quest_description.rb
class QuestDescription
  include Mongoid::Document
  include Mongoid::Timestamps

  field :active, type: Boolean, default: true
  field :type, type: Symbol, default: :quest
  field :name, type: String
  field :description, type: String
  field :points, type: Integer, default: 1
  field :bonus_approval_points, type: Integer, default: 1
  field :bonus_sharing_points, type: Integer, default: 1
  field :approvals_required_for_points, type: Integer, default: 1
  field :approvals_required_for_bonus, type: Integer, default: 1

  embedded_in :branch

  scope :photo, where(type: :photo)
  scope :review, where(type: :review)
  scope :comment, where(type: :comment)
  scope :facebook_like, where(type: :facebook_like)
  scope :twitter_follow, where(type: :twitter_follow)


  def start(person)
    patron = person.patrons.where(branch_id: self.branch.id)
    patron = person.patronize(branch) if patron.nil?
    patron.start_quest(self)
  end
end

app/controllers/admin/quest_description_controller.rb
class Admin::QuestDescriptionController < Admin::AdminController
  before_action :set_context

  def index
  end

  def new
    @quest_description = @flash_quest_branch.quest_descriptions.build
  end

  def edit
    @quest_description = @branch.quest_descriptions.find(params[:id])
  end

  def create
    @quest_description = @flash_quest_branch.quest_descriptions.create! quest_description_params
    redirect_to action: :index
  end

  def update
    @quest_description.update_attributes! quest_description_params
    redirect_to action: :index
  end

  private

  def set_context
    @biz = Business.find(params[:business_id])
    @branch = @biz.branches.find(params[:branch_id])
    @quest_descriptions = @branch.quest_descriptions
    @quest_description = @branch.quest_descriptions.find(params[:id]) if params[:id]
  end

  def quest_description_params
    params.require(:quest_description).permit(
      :active,
      :type,
      :name,
      :description,
      :points,
      :approvals_required_for_points,
      # :bonus_approval_points,
      # :bonus_sharing_points,
      # :approvals_required_for_bonus
    )
  end
end

app/controllers/admin/quest_descriptions_controller.rb
class Admin::QuestDescriptionsController < Admin::AdminController
  before_action :set_context

  def index
  end

  def new
    @quest_type =  params[:quest_type] || :photo
    @quest_description = @branch.quest_descriptions.build
  end

  def edit
    @quest_description = @branch.quest_descriptions.find(params[:id])
  end

  def create
    @quest_description = @branch.quest_descriptions.create! quest_description_params
    redirect_to action: :index
  end

  def update
    @quest_description.update_attributes! quest_description_params
    redirect_to action: :index
  end

  def destroy
    @branch.quest_descriptions.find(params[:id]).delete
    redirect_to action: :index
  end

  private

  def set_context
    @biz = Business.unscoped.find(params[:business_id])
    @branch = @biz.branches.unscoped.find(params[:branch_id])
    @photo_quest_descriptions = @branch.quest_descriptions.photo
    @comment_quest_descriptions = @branch.quest_descriptions.comment
    @twitter_follow_quest_descriptions = @branch.quest_descriptions.twitter_follow
    @facebook_like_quest_descriptions = @branch.quest_descriptions.facebook_like
    @quest_description = @branch.quest_descriptions.find(params[:id]) if params[:id]
  end

  def quest_description_params
    params.require(:quest_description).permit(
      :active,
      :type,
      :name,
      :description,
      :points,
      :approvals_required_for_points,
      # :bonus_approval_points,
      # :bonus_sharing_points,
      # :approvals_required_for_bonus
    )
  end
end

app/views/admin/quest_descriptions/_form.html.haml
- quest_type ||= :photo
= f.input :points, as: :numeric, input_html: { min: 1 }
= f.hidden_field :type, value: quest_type
= f.input :name, label: :Title, placeholder: :title
= f.input :description, as: :text, placeholder: :description, input_html: {rows: 3, cols: 50}
= f.input :active, as: :radio, selected: 'Yes'
/ = f.input :approvals_required_for_points, label: 'Approvals Required', disabled: true, as: :numeric, input_html: { min: 0 }
= f.submit 'Save'
= link_to :Cancel, :back

app/views/admin/quest_descriptions/_quest_description.html.haml
- qd = quest_description
.quest-description.card
  %a{class: :points, href: edit_admin_business_branch_quest_description_path(@biz, @branch, qd) }= qd.points
  .name= qd.name
  / .type= qd.type
  .description= qd.description
  %hr
  - if 'true'.eql? qd.active.to_s.downcase
    .active Active
  - else 
    .inactive Inactive
  = link_to 'x', admin_business_branch_quest_description_path(@biz, @branch, qd), confirm: "Delete #{qd.name}?", method: :delete, class: :delete

app/views/admin/quest_descriptions/edit.html.haml
.center
  = simple_form_for @quest_description, url: admin_business_branch_quest_description_path(@biz, @branch, @quest_description) do |f|
    %h1 Update #{@quest_description.type.to_s.capitalize} Quest
    =render 'form', f: f, quest_type: @quest_description.type

app/views/admin/quest_descriptions/index.html.haml
%h1 #{@branch.name} Quest Descriptions

%h2
  Photo Quests
  %a{class: :add, href: new_admin_business_branch_quest_description_path(@biz, @branch, quest_type: :photo) } +
%hr
= render @photo_quest_descriptions

%h2
  Comment Quests
  %a{class: :add, href: new_admin_business_branch_quest_description_path(@biz, @branch, quest_type: :comment) } +
%hr
= render @comment_quest_descriptions

%h2
  Twitter Quests
  %a{class: :add, href: new_admin_business_branch_quest_description_path(@biz, @branch, quest_type: :twitter_follow) } +
%hr
= render @twitter_follow_quest_descriptions

%h2
  Facebook Quests
  %a{class: :add, href: new_admin_business_branch_quest_description_path(@biz, @branch, quest_type: :facebook_like) } +
%hr
= render @facebook_like_quest_descriptions

app/views/admin/quest_descriptions/new.html.haml
.center
  = simple_form_for @quest_description, url: admin_business_branch_quest_descriptions_path(@biz, @branch) do |f|
    %h1 Define a new #{@quest_type.to_s.titleize} Quest
    =render 'form', f: f, quest_type: @quest_type